FROM ubuntu:zesty

RUN groupadd --gid 1000 node \
  && useradd --uid 1000 --gid node --shell /bin/bash --create-home node

RUN apt-get update && apt-get install -y curl software-properties-common

RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -

RUN curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable"

RUN apt-get update && \
    apt-get install -y nodejs docker-ce google-chrome-stable build-essential

RUN npm install -g yarn
